### ISSUE TITLE
【点播】跳转

### ISSUE THREAD

**Issue by bmi-tech** [bmi-tech/skyvis#2]

**Comment by bmi-tech** [comment]
后退跳转：客户端是否会缓存已下载文件？还是会向服务器请求下载对应 ts 文件？

**Comment by bmi-tech** [comment]
前进跳转：标准 HLS协议不支持前进跳转，只能在已经下载的时间范围内跳转。所以客户端是否会重新发起一个点播请求？

**Comment by bmi-tech** [comment]
跳转的及时性：保存完整的压缩文件存储的情况下，如果s3对象存储不支持流的跳转，就没有办法保证客户端点播跳转操作时的及时响应，因为需要把流保存到指定的跳转位置才能进行转码并返回给客户端

**Comment by bmi-tech** [comment]
关于 OSS：目前看到oss（oss与s3定义是相同的，都是只对象存储）对象存储支持以流的方式读取文件，所以当从文件开头进行点播时能够保证响应时间的实时性；但是oss不支持流的跳转读取操作，因此没有办法保证客户端跳转操作的实时性。

**Comment by Eson-Jia** [comment]
> 跳转的及时性：保存完整的压缩文件存储的情况下，如果s3对象存储不支持流的跳转，就没有办法保证客户端点播跳转操作时的及时响应，因为需要把流保存到指定的跳转位置才能进行转码并返回给客户端

关于 OSS：目前看到oss（oss与s3定义是相同的，都是只对象存储）对象存储支持以流的方式读取文件，所以当从文件开头进行点播时能够保证响应时间的实时性；但是oss不支持流的跳转读取操作，因此没有办法保证客户端跳转操作的实时性。
